export const DRIVER_INFO_FORMS = "Driver Info Forms";
export const ANSWERS = "Answers";
export const FLESLAND_1 = "flesland1";
export const FLESLAND_2 = "flesland2";
export const FLESLAND_3 = "flesland3";
export const FLESLAND_4 = "flesland4";
export const NO_ANSWERS = "No Answers Yet. Find a customer that can fill your Live Form! Click Refresh if the result don't show automatically.";
export const FLESLAND_1_TITLE = "Flesland 1"
export const FLESLAND_2_TITLE = "Flesland 2"
export const FLESLAND_3_TITLE = "Flesland 3"
export const FLESLAND_4_TITLE = "Flesland 4"
export const UKNOWN_FORM = "Uknown Form";